services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: kishorb
      MONGO_INITDB_ROOT_PASSWORD: kishorb
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    command: redis-server --requirepass kishorb
    volumes:
      - redis_data:/data
    networks:
      - app-network
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/db

  url_shortener:
    build:
      context: .
      dockerfile: Dockerfile
    image: url_shortener:latest
    container_name: url_shortener
    restart: unless-stopped
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://kishorb:kishorb@mongodb:27017/url_shortener?authSource=admin
      - REDIS_URL=redis://:kishorb@redis:6379
      - NODE_ENV=production
      - DOMAIN=http://localhost:5000
      - MACHINE_ID=M1
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network
    ports:
      - "5000:5000"

volumes:
  mongodb_data:
  redis_data:
  redisinsight_data:

networks:
  app-network:
    driver: bridge
